twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals: 
        name: 'Guyot Mathieu'
        address: '1 avenue de Fribourg 68000 Colmar'
        email: '%env(ADMIN_EMAIL)%'
        company: '%env(ADMIN_COMPANY)%'
        telephone: '06.63.02.79.29'
        siret: '83218902100021'
        ape: '6201Z'
        tva: 'non applicable ART.293B du CGI'
        quantity: '1'
        host: 'ionos'
        domain: 'easywebjob.fr'
when@test:
    twig:
        strict_variables: true
